version: 2.1

jobs:
  build:
    docker: 
      - image: vnvna/cpp-cnv:ubuntu-0.0.1
    steps:
      - run: "git config --global --add safe.directory /tmp/_circleci_local_build_repo"
      - checkout
      - run: "cmake -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE:STRING=Release -S./ -B./build -G Ninja"
      - run: "cmake --build ./build"

workflows:
  main:
    jobs:
      - build

